src/Entity/RoomRating.php
<?php

namespace App\Entity;

use App\Repository\RoomRatingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RoomRatingRepository::class)]
class RoomRating
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $comment = null;

    #[ORM\Column]
    private ?int $rating = null;

    #[ORM\ManyToOne(inversedBy: 'client')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $client = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $Posted_At = null;

    #[ORM\ManyToOne(inversedBy: 'roomRatings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Salle $Room = null;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getClient(): ?User
    {
        return $this->client;
    }

    public function setClient(?User $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getPostedAt(): ?\DateTimeImmutable
    {
        return $this->Posted_At;
    }

    public function setPostedAt(\DateTimeImmutable $Posted_At): static
    {
        $this->Posted_At = $Posted_At;

        return $this;
    }

    public function getRoom(): ?salle
    {
        return $this->Room;
    }

    public function setRoom(?salle $Room): static
    {
        $this->Room = $Room;

        return $this;
    }
}

src/Controller/SeeRatingsController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Salle;
use App\Entity\RoomRating;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SeeRatingsController extends AbstractController
{
    #[Route('/see/ratings/{id}', name: 'app_see_ratings')]
    public function index(ManagerRegistry $doctrine, $id, Security $security): Response
    {

        if (!$security->isGranted('IS_NOT_BANNED')) {
            return $this->redirectToRoute('app_home');
        }

        $ratings = $doctrine->getRepository(RoomRating::class)->findAll();
        $ratingAuthor = $doctrine->getRepository(RoomRating::class)->getRatingAuthor($id);
        $salle = $doctrine->getRepository(Salle::class)->find($id);
        $users = $doctrine->getRepository(User::class)->findAll();
        $avgRating = $doctrine->getRepository(RoomRating::class)->getAverageRating($id);

        return $this->render('see_ratings/index.html.twig', [
            'ratings' => $ratings,
            'ratingAuthor' => $ratingAuthor,
            'users' => $users,
            'salle' => $salle,
            'avgRating' => $avgRating
        ]);
    }

    

    #[Route('/rating/delete/{id}', name: 'app_rating_delete')]
    public function delete(EntityManagerInterface $em, RoomRating $rating, $id, Security $security): Response
    {
        if(!$security->isGranted('ROLE_ADMIN')){
            return $this->redirectToRoute('app_home');
        }

        $roomId = $rating->getRoom()->getId();
        $rating = $em->getRepository(RoomRating::class)->find($id);
        $em->remove($rating);
        $em->flush();

        return $this->redirectToRoute('app_see_ratings', ['id' => $roomId]);
    }
}

templates/see_ratings/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis
{% endblock %}

    
    {% block body %}
<section class="container">
<div class="row">
{% for r in ratingAuthor %}
    {% if loop.index0 == 0 %}
        <h1 class='text-center'>Avis sur la salle {{ r.room.nom }}</h1>
        <h3 class='text-center'>Note moyenne: {{ avgRating[0]['rating']|number_format(2, '.', '') }}/5</h3>
    {% endif %}
	<div class="card mb-3 mx-3" style='width: 18rem'>
		<div class="card-body mx-3">
			<h5 class="card-title">Posté par: <br>{{ r.client.firstName }} {{ r.client.lastName }}</h5>
            <p class="card-text">Note : {{ r.rating }}/5</p>
			<p class="card-text">{{ r.comment }}</p>
			<p class="card-text">
				<small class="text-body-secondary">Posté le {{ r.postedAt | date('d:m:Y') }} à {{ r.postedAt | date('H:i:s') }}</small>
			</p>
            {% if is_granted('ROLE_ADMIN') %}
                <a href="{{ path('app_rating_delete', {'id': r.id}) }}" class="btn btn-danger" onclick="return confirm('êtes vous sur de vouloir supprimer cet avis?');">Supprimer</a>
            {% endif %}
		</div>
	</div>
{% endfor %}
    </section>
</div>
{% endblock %}